-- Table des Délégations (Géographie administrative)
CREATE TABLE DELEGATION (
    CODE_DELEG VARCHAR2(10) PRIMARY KEY,
    NOM_DELEG VARCHAR2(100) NOT NULL
);

-- Table des Arrêts (Stations/Gares)
CREATE TABLE ARRET (
    CODE_ARRET VARCHAR2(20) PRIMARY KEY,
    NOM_ARRET VARCHAR2(150) NOT NULL,
    LATITUDE NUMBER(9,6), -- Ex: 35.678123
    LONGITUDE NUMBER(9,6), -- Ex: 10.098765
    CODE_DELEG VARCHAR2(10),
    CONSTRAINT FK_ARRET_DELEG FOREIGN KEY (CODE_DELEG) REFERENCES DELEGATION(CODE_DELEG)
);

-- Table des Catégories de Véhicules
CREATE TABLE CATEGORIE_VEHICULE (
    ID_CATEGORIE NUMBER PRIMARY KEY,
    LIBELLE_CATEGORIE VARCHAR2(50) NOT NULL, -- Ex: 'BUS STANDARD', 'MICROCAR'
    NOMBRE_PLACES NUMBER
);

-- Table des Véhicules (Flotte)
CREATE TABLE VEHICULE (
    MATRICULE VARCHAR2(20) PRIMARY KEY,
    ID_CATEGORIE NUMBER,
    CONSTRAINT FK_VEHICULE_CATEG FOREIGN KEY (ID_CATEGORIE) REFERENCES CATEGORIE_VEHICULE(ID_CATEGORIE)
);

-- Table des Agents (Chauffeurs/Personnel)
CREATE TABLE AGENT (
    MATRICULE_AGENT VARCHAR2(20) PRIMARY KEY,
    NOM_PRENOM VARCHAR2(150) NOT NULL,
    QUALIFICATION VARCHAR2(50),
    CODE_DELEG VARCHAR2(10),
    CONSTRAINT FK_AGENT_DELEG FOREIGN KEY (CODE_DELEG) REFERENCES DELEGATION(CODE_DELEG)
);

-- Table des Lignes de Transport
CREATE TABLE LIGNE (
    ID_LIGNE VARCHAR2(20) PRIMARY KEY,
    NOM_LIGNE VARCHAR2(150) NOT NULL,
    NOM_LIGNE_AR VARCHAR2(150), -- Nom en arabe
    TYPE_LIGNE VARCHAR2(50), -- Ex: 'URBAIN', 'INTERURBAIN'
    ID_CATEGORIE_VEHICULE NUMBER,
    CONSTRAINT FK_LIGNE_CATEG FOREIGN KEY (ID_CATEGORIE_VEHICULE) REFERENCES CATEGORIE_VEHICULE(ID_CATEGORIE)
);

-- Table des Étapes d'Itinéraire (Lie la Ligne aux Arrêts dans l'ordre)
-- C'est l'équivalent de stop_times.txt + shapes.txt en GTFS
CREATE TABLE ETAPE_LIGNE (
    ID_LIGNE VARCHAR2(20),
    ORDRE_PASSAGE NUMBER,
    CODE_ARRET VARCHAR2(20),
    DISTANCE_KM NUMBER(8,2),
    DUREE_TRAJET_MIN NUMBER,
    PRIMARY KEY (ID_LIGNE, ORDRE_PASSAGE),
    CONSTRAINT FK_ETAPE_LIGNE FOREIGN KEY (ID_LIGNE) REFERENCES LIGNE(ID_LIGNE),
    CONSTRAINT FK_ETAPE_ARRET FOREIGN KEY (CODE_ARRET) REFERENCES ARRET(CODE_ARRET)
);

-- Table des Règles Tarifaires (Basé sur fare_rules.csv et fare_attibute.csv)
CREATE TABLE REGLE_TARIFAIRE (
    ID_TARIF NUMBER PRIMARY KEY,
    ID_LIGNE VARCHAR2(20),
    DISTANCE_MIN_KM NUMBER(8,2),
    DISTANCE_MAX_KM NUMBER(8,2),
    PRIX NUMBER(8,2),
    DEVISE VARCHAR2(3) DEFAULT 'TND',
    CONSTRAINT FK_TARIF_LIGNE FOREIGN KEY (ID_LIGNE) REFERENCES LIGNE(ID_LIGNE)
);