// <auto-generated />
using System;
using App.Infrastructure.DataAccessManager.EFCore.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.Infrastructure.DataAccessManager.Migrations
{
    [DbContext(typeof(CommandContext))]
    partial class CommandContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Core.Domain.Entities.DrAgent", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("DECAGEN");

                    b.Property<int>("CenterId")
                        .HasColumnType("int")
                        .HasColumnName("DECCENT");

                    b.Property<int>("DelegationId")
                        .HasColumnType("int")
                        .HasColumnName("DECDELEG");

                    b.Property<string>("FullNameAr")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("DENAGEA");

                    b.Property<string>("FullNameFr")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("DENAGEN");

                    b.Property<int>("JournalCode")
                        .HasColumnType("int")
                        .HasColumnName("DECJOUR");

                    b.Property<int?>("PdaNumber")
                        .HasColumnType("int")
                        .HasColumnName("PDA");

                    b.Property<string>("QualificationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DECQUAL");

                    b.HasKey("Id");

                    b.HasIndex("DelegationId");

                    b.ToTable("dragent", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Entities.DrCatVe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Decateg")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Deacate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DrCatVe");
                });

            modelBuilder.Entity("Core.Domain.Entities.DrDeleg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameFr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DrDeleg");
                });

            modelBuilder.Entity("Core.Domain.Entities.DrDentr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CenterId")
                        .HasColumnType("int");

                    b.Property<int>("DelegationId")
                        .HasColumnType("int");

                    b.Property<string>("FullNameAr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullNameFr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("JournalCode")
                        .HasColumnType("int");

                    b.Property<int?>("PdaNumber")
                        .HasColumnType("int");

                    b.Property<string>("QualificationCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DrDentr");
                });

            modelBuilder.Entity("Core.Domain.Entities.DrDepar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte?>("CONV")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("CONV");

                    b.Property<string>("DEAMPLI")
                        .HasColumnType("longtext")
                        .HasColumnName("DEAMPLI");

                    b.Property<string>("DEAMPLT")
                        .HasColumnType("longtext")
                        .HasColumnName("DEAMPLT");

                    b.Property<string>("DEANNUL")
                        .HasColumnType("longtext")
                        .HasColumnName("DEANNUL");

                    b.Property<short?>("DECAGE1")
                        .HasColumnType("smallint")
                        .HasColumnName("DECAGE1");

                    b.Property<short?>("DECAGEN")
                        .HasColumnType("smallint")
                        .HasColumnName("DECAGEN");

                    b.Property<byte?>("DECCENT")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("DECCENT");

                    b.Property<string>("DECCLIE")
                        .HasColumnType("longtext")
                        .HasColumnName("DECCLIE");

                    b.Property<byte?>("DECCLOT")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("DECCLOT");

                    b.Property<int?>("DECEXER")
                        .HasColumnType("int")
                        .HasColumnName("DECEXER");

                    b.Property<short?>("DECODE1")
                        .HasColumnType("smallint")
                        .HasColumnName("DECODE1");

                    b.Property<string>("DECODE2")
                        .HasColumnType("longtext")
                        .HasColumnName("DECODE2");

                    b.Property<string>("DECODE3")
                        .HasColumnType("longtext")
                        .HasColumnName("DECODE3");

                    b.Property<short?>("DECODVH")
                        .HasColumnType("smallint")
                        .HasColumnName("DECODVH");

                    b.Property<short>("DECOPER")
                        .HasColumnType("smallint")
                        .HasColumnName("DECOPER");

                    b.Property<string>("DECSEAN")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("DECSEAN");

                    b.Property<short>("DECSERV")
                        .HasColumnType("smallint")
                        .HasColumnName("DECSERV");

                    b.Property<string>("DECTYPC")
                        .HasColumnType("longtext")
                        .HasColumnName("DECTYPC");

                    b.Property<DateTime?>("DEDATED")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DEDATED");

                    b.Property<DateTime?>("DEDATES")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DEDATES");

                    b.Property<string>("DEETAT")
                        .HasColumnType("longtext")
                        .HasColumnName("DEETAT");

                    b.Property<DateTime?>("DEHEUAA")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DEHEUAA");

                    b.Property<DateTime?>("DEHEUDR")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DEHEUDR");

                    b.Property<DateTime?>("DEHEUFS")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DEHEUFS");

                    b.Property<DateTime?>("DEHEUPD")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DEHEUPD");

                    b.Property<DateTime?>("DEHEUPS")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DEHEUPS");

                    b.Property<string>("DEKMCHA")
                        .HasColumnType("longtext")
                        .HasColumnName("DEKMCHA");

                    b.Property<string>("DEKMREC")
                        .HasColumnType("longtext")
                        .HasColumnName("DEKMREC");

                    b.Property<decimal?>("DEKMTH")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("DEKMTH");

                    b.Property<byte?>("DENBRRO")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("DENBRRO");

                    b.Property<byte>("DENDEPA")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("DENDEPA");

                    b.Property<short>("DENUMLI")
                        .HasColumnType("smallint")
                        .HasColumnName("DENUMLI");

                    b.Property<string>("DEOBSER")
                        .HasColumnType("longtext")
                        .HasColumnName("DEOBSER");

                    b.Property<string>("DEORDTR")
                        .HasColumnType("longtext")
                        .HasColumnName("DEORDTR");

                    b.Property<string>("DEORIGD")
                        .HasColumnType("longtext")
                        .HasColumnName("DEORIGD");

                    b.Property<string>("DEPISTE")
                        .HasColumnType("longtext")
                        .HasColumnName("DEPISTE");

                    b.Property<int?>("NUMLOC")
                        .HasColumnType("int")
                        .HasColumnName("NUMLOC");

                    b.Property<string>("PDECAGE1")
                        .HasColumnType("longtext")
                        .HasColumnName("PDECAGE1");

                    b.Property<string>("PDECAGEN")
                        .HasColumnType("longtext")
                        .HasColumnName("PDECAGEN");

                    b.Property<string>("PDECODVH")
                        .HasColumnType("longtext")
                        .HasColumnName("PDECODVH");

                    b.Property<string>("SAE")
                        .HasColumnType("longtext")
                        .HasColumnName("SAE");

                    b.Property<string>("SCOL")
                        .HasColumnType("longtext")
                        .HasColumnName("SCOL");

                    b.Property<byte?>("VOY_MOD")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("VOY_MOD");

                    b.Property<byte?>("VOY_SUP")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("VOY_SUP");

                    b.Property<byte?>("VOY_UPD")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("VOY_UPD");

                    b.HasKey("Id");

                    b.ToTable("DrDepar", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Entities.DrItin", b =>
                {
                    b.Property<int>("Denumli")
                        .HasColumnType("int")
                        .HasColumnName("denumli");

                    b.Property<int>("Denumlg")
                        .HasColumnType("int")
                        .HasColumnName("denumlg");

                    b.Property<int>("Decstat")
                        .HasColumnType("int")
                        .HasColumnName("decstat");

                    b.Property<decimal?>("Dedurtr")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("dedurtr");

                    b.Property<decimal?>("Deescale")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("deescale");

                    b.Property<decimal?>("Dekmsta")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("dekmsta");

                    b.Property<int?>("Desecti")
                        .HasColumnType("int")
                        .HasColumnName("desecti");

                    b.HasKey("Denumli", "Denumlg", "Decstat");

                    b.ToTable("DrItin");
                });

            modelBuilder.Entity("Core.Domain.Entities.DrLigne", b =>
                {
                    b.Property<int>("Denumli")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("denumli");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Denumli"));

                    b.Property<string>("Deactif")
                        .HasColumnType("longtext")
                        .HasColumnName("deactif");

                    b.Property<int?>("Deccent")
                        .HasColumnType("int")
                        .HasColumnName("deccent");

                    b.Property<int?>("Decdeleg")
                        .HasColumnType("int")
                        .HasColumnName("decdeleg");

                    b.Property<decimal?>("Dectyli")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("dectyli");

                    b.Property<string>("Dectyta")
                        .HasColumnType("longtext")
                        .HasColumnName("dectyta");

                    b.Property<string>("Denatli")
                        .HasColumnType("longtext")
                        .HasColumnName("denatli");

                    b.Property<decimal?>("Denbrkm")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("denbrkm");

                    b.Property<string>("Denomla")
                        .HasColumnType("longtext")
                        .HasColumnName("denomla");

                    b.Property<string>("Denomli")
                        .HasColumnType("longtext")
                        .HasColumnName("denomli");

                    b.Property<string>("IntegBi")
                        .HasColumnType("longtext")
                        .HasColumnName("integ_bi");

                    b.Property<string>("Sae")
                        .HasColumnType("longtext")
                        .HasColumnName("sae");

                    b.Property<string>("Siv")
                        .HasColumnType("longtext")
                        .HasColumnName("siv");

                    b.HasKey("Denumli");

                    b.ToTable("DrLigne");
                });

            modelBuilder.Entity("Core.Domain.Entities.DrStati", b =>
                {
                    b.Property<int>("DecStat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DECSTAT");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DecStat"));

                    b.Property<string>("DateSys")
                        .HasColumnType("longtext")
                        .HasColumnName("DATE_SYS");

                    b.Property<string>("DecLoca")
                        .HasColumnType("longtext")
                        .HasColumnName("DECLOCA");

                    b.Property<string>("DecRout")
                        .HasColumnType("longtext")
                        .HasColumnName("DECROUT");

                    b.Property<string>("DecTyst")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("DECTYST");

                    b.Property<string>("DelStaA")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("DELSTAA");

                    b.Property<string>("DelStat")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("DELSTAT");

                    b.Property<string>("LocationType")
                        .HasColumnType("longtext")
                        .HasColumnName("LOCATION_TYPE");

                    b.Property<string>("ParentStation")
                        .HasColumnType("longtext")
                        .HasColumnName("PARENT_STATION");

                    b.Property<int>("Rayon")
                        .HasColumnType("int")
                        .HasColumnName("RAYON");

                    b.Property<string>("StopDesc")
                        .HasColumnType("longtext")
                        .HasColumnName("STOP_DESC");

                    b.Property<string>("StopLat")
                        .HasColumnType("longtext")
                        .HasColumnName("STOP_LAT");

                    b.Property<string>("StopLon")
                        .HasColumnType("longtext")
                        .HasColumnName("STOP_LON");

                    b.Property<string>("StopTimezone")
                        .HasColumnType("longtext")
                        .HasColumnName("STOP_TIMEZONE");

                    b.Property<string>("StopUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("STOP_URL");

                    b.Property<string>("ZoneId")
                        .HasColumnType("longtext")
                        .HasColumnName("ZONE_ID");

                    b.HasKey("DecStat");

                    b.ToTable("DrStati");
                });

            modelBuilder.Entity("Core.Domain.Entities.DrTyLi", b =>
                {
                    b.Property<int>("Dectyli")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("dectyli");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Dectyli"));

                    b.Property<string>("Deltyla")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("deltyla");

                    b.Property<string>("Deltyli")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("deltyli");

                    b.HasKey("Dectyli");

                    b.ToTable("DrTyLi");
                });

            modelBuilder.Entity("Core.Domain.Entities.DrVehic", b =>
                {
                    b.Property<int>("Decodvh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DECODVH");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Decodvh"));

                    b.Property<int>("Deactif")
                        .HasColumnType("int")
                        .HasColumnName("deactif");

                    b.Property<int>("Decatvh")
                        .HasColumnType("int")
                        .HasColumnName("DECATVH");

                    b.Property<int?>("Decdeleg")
                        .HasColumnType("int")
                        .HasColumnName("DECDELEG");

                    b.Property<int?>("Decent")
                        .HasColumnType("int")
                        .HasColumnName("DECCENT");

                    b.Property<DateTime>("Dedatec")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DEDATEC");

                    b.Property<string>("Dematri")
                        .HasColumnType("longtext")
                        .HasColumnName("DEMATRI");

                    b.Property<int>("Denbrpa")
                        .HasColumnType("int")
                        .HasColumnName("DENBRPA");

                    b.Property<int?>("Denbrpd")
                        .HasColumnType("int")
                        .HasColumnName("DENBRPD");

                    b.HasKey("Decodvh");

                    b.ToTable("DrVehic");
                });

            modelBuilder.Entity("Core.Domain.Entities.FareAttribute", b =>
                {
                    b.Property<int>("FareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FARE_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FareId"));

                    b.Property<string>("AgencyId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("AGENCY_ID");

                    b.Property<string>("CurrencyType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CURRENCY_TYPE");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int")
                        .HasColumnName("PAYMENT_METHOD");

                    b.Property<double>("Price")
                        .HasColumnType("double")
                        .HasColumnName("PRICE");

                    b.Property<double>("PriceConf")
                        .HasColumnType("double")
                        .HasColumnName("PRICE_CONF");

                    b.Property<string>("PriceRedu")
                        .HasColumnType("longtext")
                        .HasColumnName("PRICE_REDU");

                    b.Property<int>("Transfers")
                        .HasColumnType("int")
                        .HasColumnName("TRANSFERS");

                    b.Property<string>("TypeTarif")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TYPE_TARIF");

                    b.HasKey("FareId");

                    b.ToTable("fare_attibute");
                });

            modelBuilder.Entity("Core.Domain.Entities.FareRule", b =>
                {
                    b.Property<int>("FareId")
                        .HasColumnType("int")
                        .HasColumnName("FARE_ID");

                    b.Property<int>("RouteId")
                        .HasColumnType("int")
                        .HasColumnName("ROUTE_ID");

                    b.Property<int>("AuId")
                        .HasColumnType("int")
                        .HasColumnName("AU_ID");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int")
                        .HasColumnName("DESTINATION_ID");

                    b.Property<int>("DuId")
                        .HasColumnType("int")
                        .HasColumnName("DU_ID");

                    b.Property<int>("OriginId")
                        .HasColumnType("int")
                        .HasColumnName("ORIGIN_ID");

                    b.Property<string>("Section")
                        .HasColumnType("longtext")
                        .HasColumnName("SECTION");

                    b.Property<string>("TypeTarif")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TYPE_TARIF");

                    b.HasKey("FareId", "RouteId");

                    b.ToTable("Fare_Rules");
                });

            modelBuilder.Entity("Core.Domain.Entities.Identity.Token", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedById")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<DateTimeOffset>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedById")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.HasKey("Id");

                    b.ToTable("Token");
                });

            modelBuilder.Entity("Core.Domain.Entities.StopTime", b =>
                {
                    b.Property<DateTime>("Dedated")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DEDATED");

                    b.Property<int>("TripId")
                        .HasColumnType("int")
                        .HasColumnName("TRIP_ID");

                    b.Property<int>("StopSequence")
                        .HasColumnType("int")
                        .HasColumnName("STOP_SEQUENCE");

                    b.Property<DateTime?>("ArrivalTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ARRIVAL_TIME");

                    b.Property<int>("DecStat")
                        .HasColumnType("int")
                        .HasColumnName("DECSTAT");

                    b.Property<DateTime?>("DepartureTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DEPARTURE_TIME");

                    b.Property<int?>("PickupType")
                        .HasColumnType("int")
                        .HasColumnName("PICKUP_TYPE");

                    b.Property<DateTime?>("RtArrivalTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("RT_ARRIVAL_TIME");

                    b.Property<DateTime?>("RtDepartureTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("RT_DEPARTURE_TIME");

                    b.Property<string>("ShapeDistTraveled")
                        .HasColumnType("longtext")
                        .HasColumnName("SHAPE_DIST_TRAVELED");

                    b.Property<int?>("State")
                        .HasColumnType("int")
                        .HasColumnName("STATE");

                    b.Property<int?>("Timepoint")
                        .HasColumnType("int")
                        .HasColumnName("TIMEPOINT");

                    b.HasKey("Dedated", "TripId", "StopSequence");

                    b.ToTable("Stop_Times");
                });

            modelBuilder.Entity("Core.Domain.Entities.Trip", b =>
                {
                    b.Property<DateTime>("Dedated")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DEDATED");

                    b.Property<int>("TripId")
                        .HasColumnType("int")
                        .HasColumnName("TRIP_ID");

                    b.Property<int>("Denomli")
                        .HasColumnType("int")
                        .HasColumnName("DENUMLI");

                    b.Property<int>("DirectionId")
                        .HasColumnType("int")
                        .HasColumnName("DIRECTION_ID");

                    b.Property<int>("Alert")
                        .HasColumnType("int")
                        .HasColumnName("ALERT");

                    b.Property<int>("AvanceRetard")
                        .HasColumnType("int")
                        .HasColumnName("AVANCE_RETARD");

                    b.Property<int>("BusPr")
                        .HasColumnType("int")
                        .HasColumnName("BUS_PR");

                    b.Property<int>("BusRe")
                        .HasColumnType("int")
                        .HasColumnName("BUS_RE");

                    b.Property<int>("Changement")
                        .HasColumnType("int")
                        .HasColumnName("CHANGEMENT");

                    b.Property<int?>("ChauffPr")
                        .HasColumnType("int")
                        .HasColumnName("CHAUFF_PR");

                    b.Property<int?>("ChauffRe")
                        .HasColumnType("int")
                        .HasColumnName("CHAUFF_RE");

                    b.Property<int>("Devalid")
                        .HasColumnType("int")
                        .HasColumnName("DEVALID");

                    b.Property<int?>("Etat")
                        .HasColumnType("int")
                        .HasColumnName("ETAT");

                    b.Property<int?>("Grp")
                        .HasColumnType("int")
                        .HasColumnName("GRP");

                    b.Property<int?>("Haveret")
                        .HasColumnType("int")
                        .HasColumnName("HAVERET");

                    b.Property<string>("MetaData")
                        .HasColumnType("longtext")
                        .HasColumnName("META_DATA");

                    b.Property<int?>("RecPr")
                        .HasColumnType("int")
                        .HasColumnName("REC_PR");

                    b.Property<int?>("RecRe")
                        .HasColumnType("int")
                        .HasColumnName("REC_RE");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("SERVICE_ID");

                    b.Property<DateTime?>("TimeArriveR")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("TIME_ARRIVE_R");

                    b.Property<DateTime?>("TimeDepart")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("TIME_DEPART");

                    b.Property<DateTime?>("TimeDepartR")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("TIME_DEPART_R");

                    b.Property<string>("TimeNret")
                        .HasColumnType("longtext")
                        .HasColumnName("TIME_NRET");

                    b.Property<int?>("TripNid")
                        .HasColumnType("int")
                        .HasColumnName("TRIP_NID");

                    b.Property<int?>("Vmax")
                        .HasColumnType("int")
                        .HasColumnName("VMAX");

                    b.HasKey("Dedated", "TripId", "Denomli", "DirectionId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("Core.Domain.Identity.AspNetIdentity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .HasColumnType("longtext");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedById")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("IsBlocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ProfilePictureName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedById")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("FirstName");

                    b.HasIndex("LastName");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("UserName");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Entities.DrAgent", b =>
                {
                    b.HasOne("Core.Domain.Entities.DrDeleg", null)
                        .WithMany("Agents")
                        .HasForeignKey("DelegationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Core.Domain.Identity.AspNetIdentity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Core.Domain.Identity.AspNetIdentity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Identity.AspNetIdentity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Core.Domain.Identity.AspNetIdentity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domain.Entities.DrDeleg", b =>
                {
                    b.Navigation("Agents");
                });
#pragma warning restore 612, 618
        }
    }
}
